### ISSUE TITLE
Some PDFs throw Invalid PDF structure error

### ISSUE THREAD

**Issue by kanatkubash** [lublak/pdfdataextract#1]
Library is failing to read some PDF files which are opened without problem in browsers (Chrome, Firefox )
Exception stack is 

`
(node:9244) UnhandledPromiseRejectionWarning: Error
    at BaseExceptionClosure (C:\Users\kanat\Desktop\kivra_android\node_modules\pdfjs-dist\es5\build\pdf.js:2166:29)
    at Object.__webpack_modules__ (C:\Users\kanat\Desktop\kivra_android\node_modules\pdfjs-dist\es5\build\pdf.js:2169:2)
    at __w_pdfjs_require__ (C:\Users\kanat\Desktop\kivra_android\node_modules\pdfjs-dist\es5\build\pdf.js:26607:42)
    at Object.__webpack_modules__ (C:\Users\kanat\Desktop\kivra_android\node_modules\pdfjs-dist\es5\build\pdf.js:306:13)
    at __w_pdfjs_require__ (C:\Users\kanat\Desktop\kivra_android\node_modules\pdfjs-dist\es5\build\pdf.js:26607:42)
    at Object.__webpack_modules__ (C:\Users\kanat\Desktop\kivra_android\node_modules\pdfjs-dist\es5\build\pdf.js:237:22)
    at __w_pdfjs_require__ (C:\Users\kanat\Desktop\kivra_android\node_modules\pdfjs-dist\es5\build\pdf.js:26607:42)
    at C:\Users\kanat\Desktop\kivra_android\node_modules\pdfjs-dist\es5\build\pdf.js:26630:18
    at C:\Users\kanat\Desktop\kivra_android\node_modules\pdfjs-dist\es5\build\pdf.js:26631:12
    at webpackUniversalModuleDefinition (C:\Users\kanat\Desktop\kivra_android\node_modules\pdfjs-dist\es5\build\pdf.js:25:20)
(node:9244) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
`
Error message : Invalid PDF structure.

Attaching PDF file. Would be great if you could look at it. Thanks
[online-21-05-04,157.9,1438721330.pdf](https://github.com/lublak/pdfdataextract/files/6493244/online-21-05-04.157.9.1438721330.pdf)

**Comment by kanatkubash** [comment]
It seems problem is in `pdfdataextractor.parseOutline` function. It receives `outlineData` argument with null value and it fails when trying to iterate it here : `for (const o of outlineData) {`. 

I added null check there and it worked

**Comment by lublak** [comment]
@kanatkubash thank you for you bug report and also that you have already researched yourself.
Sorry for the late reply. I have fixed the outline error for the next version.
Unfortunately there is another bug which will be fixed in the next pdf-dist (pre release 2.8.335).
At the moment I'm still waiting, but I think I'll publish a pre-release of pdfdataextract with every pre-release of pdf dist, so you can use the pre-release version for the time being.

**Comment by kanatkubash** [comment]
Thank you for the fix. Could you please update npm version also ?

**Comment by lublak** [comment]
@kanatkubash the new version is now online.
